title: 'stmichaelist.github.io'
description: "My Journey"
baseurl: ""
url: "https://stmichaelist.github.io"

header_pages:
  - home.md
  - peter.md
  - about.md

style: light

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
